### ISSUE TITLE
Plone 5 compatibility

### ISSUE THREAD

**Issue by cdw9** [collective/collective.recipe.plonesite#15]
I created a new Plone 5 buildout using sixieskel, and ran into this error:

    2015-10-16 14:34:48 INFO collective.recipe.plonesite Added Plone Site
    Traceback (most recent call last):
      File "/Users/chrissy/projects/products/project/parts/instance/bin/interpreter", line 274, in <module>
        exec(_val)
      File "<string>", line 1, in <module>
      File "/Users/chrissy/projects/products/project/eggs/collective.recipe.plonesite-1.9.2-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 367, in <module>
        main(app, parser)  # NOQA
      File "/Users/chrissy/projects/products/project/eggs/collective.recipe.plonesite-1.9.2-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 248, in main
        profiles_initial, site_replace, default_language)
      File "/Users/chrissy/projects/products/project/eggs/collective.recipe.plonesite-1.9.2-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 121, in create
        setDefaultLanguageOnPortalLanguages(plone, default_language)
      File "/Users/chrissy/projects/products/project/eggs/collective.recipe.plonesite-1.9.2-py2.7.egg/collective/recipe/plonesite/plonesite.py", line 132, in setDefaultLanguageOnPortalLanguages
        portal_languages = plone.portal_languages
    AttributeError: portal_languages

The buildout finished once I removed the `plonesite` part

**Comment by claytron** [comment]
See the PR in #14, I think that will fix things up.

**Comment by cdw9** [comment]
merged and released 1.9.3
