### ISSUE TITLE
Running GS steps with plonesite part against Plone 5 site fails on jquery.highlightsearchterms.js

### ISSUE THREAD

**Issue by calvinhp** [collective/collective.recipe.plonesite#17]
```
2016-10-07 11:00:44 ERROR plone.subrequest Error handling subrequest to http:///jquery.highlightsearchterms.js
Traceback (most recent call last):
  File "/Volumes/pool/Projects/PloneTraining/plone5training/eggs/plone.subrequest-1.7.0-py2.7.egg/plone/subrequest/__init__.py", line 143, in subrequest
    traversed = request.traverse(path)
  File "/Volumes/pool/Projects/PloneTraining/plone5training/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 508, in traverse
    subobject = self.traverseName(object, entry_name)
  File "/Volumes/pool/Projects/PloneTraining/plone5training/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 352, in traverseName
    ob2 = adapter.publishTraverse(self, name)
  File "/Volumes/pool/Projects/PloneTraining/plone5training/eggs/Products.CMFPlone-5.0.5-py2.7.egg/Products/CMFPlone/browser/admin.py", line 45, in publishTraverse
    return DefaultPublishTraverse.publishTraverse(self, request, name)
  File "/Volumes/pool/Projects/PloneTraining/plone5training/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 105, in publishTraverse
    raise e
NotFound:   <h2>Site Error</h2>
  <p>An error was encountered while publishing this resource.
  </p>
  <p><strong>Resource not found</strong></p>

  Sorry, the requested resource does not exist.<p>Check the URL and try again.</p><p><b>Resource:</b> jquery.highlightsearchterms.js
GET</p>
  <hr noshade="noshade"/>

  <p>Troubleshooting Suggestions</p>

  <ul>
  <li>The URL may be incorrect.</li>
  <li>The parameters passed to this resource may be incorrect.</li>
  <li>A resource that this resource relies on may be
      encountering an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>
> /Volumes/pool/Projects/PloneTraining/plone5training/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py(105)publishTraverse()
-> raise e
```

**Comment by flipmcf** [comment]
https://github.com/plone/Products.CMFPlone/issues/1811
