### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by tisto** [collective/collective.recipe.plonesite#21]
Buildout run does not fail on Python3 but creating the Plone instance does not work either:

```
Traceback (most recent call last):
  File "/Users/timo/workspace/kitconcept/XXX/api/parts/instance/bin/interpreter", line 277, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
  File "/Users/timo/.buildout/eggs/collective.recipe.plonesite-1.9.5-py3.7.egg/collective/recipe/plonesite/plonesite.py", line 237
    except Exception, e:  # remove Exception as, to keep py2.4 support
                    ^
SyntaxError: invalid syntax
```

**Comment by tisto** [comment]
Fixed in https://github.com/collective/collective.recipe.plonesite/pull/22
